services:
  datagatherer:
    build:
      context: ./DataGatherer
      dockerfile: Dockerfile
    entrypoint: ["python", "DataGatherer.py"]
    command: [
      "--seed", "https://en.wikipedia.org/wiki/Main_Page",
      "--timeout", "60",
      "--scrapers", "8",
      "--validators", "1",
      "--redis_host", "localhost",
      "--redis_port", "6379"
    ]

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"