services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "pw"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pw"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  datagatherer:
    build:
      context: ./DataGatherer
      dockerfile: Dockerfile
    restart: on-failure
    entrypoint: ["python", "DataGatherer.py"]
    command: [
      "--seed", "https://en.wikipedia.org/wiki/Main_Page",
      "--timeout", "60",
      "--scrapers", "8",
      "--validators", "1",
      "--redis_host", "cache",
      "--redis_port", "6379"
    ]

  indexer:
    build:
      context: ./Indexer
      dockerfile: Dockerfile
    entrypoint: ["python", "Indexer.py"]
    command: [
      "--timeout", "240",
      "--redis_host", "cache",
      "--redis_port", "6379"
    ]

  databaser:
    build:
      context: ./Databaser
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["python", "Databaser.py"]
    command: [
      "--timeout", "240",
      "--sync_period", "15",
      "--redis_host", "cache",
      "--redis_port", "6379",
      "--mysql_host", "mysql",
      "--mysql_port", "3306",
      "--mysql_user", "user",
      "--mysql_password", "pw",
      "--mysql_database", "db"
    ]